const sections = [
    { "Home": null },
    {
        "Regions": ["Africa",
            "Asia",
            "Canada",
            "China",
            "Europe",
            "Latin America",
            "Middle East"],
        "Sections": ["Economy"],
        "More": ["World Video"]
    },
    {
        "Sections": ["Economy",
            "Law",
            "New York",
            "Politics"],
        "Columns & Blogs": ["Real Time Economics",
            "Washington Wire",],
        "More": ["Journal Report",
            "U.S. Video",
            "What's News Podcast",]
    },
    {
        "Sections": ["Election 2020",
            "Campaign Wire",],
        "More": ["WSJ/NBC News Poll",
            "Politics Video",]
    },
    {
        "Blogs": ["Real Time Economics"],
        "WSJ Pro": ["Bankruptcy",
            "Central Banking",
            "Private Equity",
            "Strategic Intelligence",
            "Venture Capital",],
        "More": ["Economic Forecasting Survey",
            "Economy Video",]
    },
    {
        "Sections": ["Management",
            "Tech/WSJ.D",
            "The Future of Everything",],
        "Industries": ["Aerospace & Defense",
            "Autos & Transportation",
            "Commercial Real Estate",
            "Consumer Products",
            "Energy",
            "Entrepreneurship",
            "Financial Services",
            "Food & Services",
            "Health Care",
            "Hospitality",
            "Law",
            "Manufacturing",
            "Media & Marketing",
            "Natural Resources",
            "Retail",],
        "C-Suite": ["CFO Journal",
            "CIO Journal",
            "CMO Today",
            "Logistics Report",
            "Risk & Compliance",
            "The Experience Report",],
        "Columns": ["Heard on the Street",],
        "WSJ Pro": ["Artificial Intelligence",
            "Bankruptcy",
            "Central Banking",
            "Cybersecurity",
            "Private Equity",
            "Strategic Intelligence",
            "Venture Capital",],
        "More": ["Business Video",
            "Journal Report",
            "Business Podcast",]
    },
    {
        "Sections": ["CIO Journal",
            "The Future of Everything",],
        "Columns & Blogs": ["Christopher Mims",
            "Joanna Stern",
            "Julie Jargon",],
        "More": ["Billion Dollar Startup Club",
            "Tech Video",
            "Tech Podcast",
            "Startup Stock Tracker",]
    },
    {
        "Sections": ["Bonds",
            "Commercial Real Estate",
            "Commodities & Futures",
            "Stocks",
            "Personal Finance",
            "WSJ Money",],
        "Columns & Blogs": ["Heard on the Street",
            "MoneyBeat",
            "Wealth Adviser",],
        "Market Data": ["Market Data Home",
            "U.S. Stocks",
            "Currencies",
            "Commodities",
            "Bonds & Rates",
            "Mutual Funds & ETFs",],
        "More": ["CFO Journal",
            "Journal Report",
            "Markets Video",
            "Your Money Briefing Podcast",
            "Secrets of Wealthy Women ",
            "Search Quotes and Companies",]
    },
    {
        "Columnists": ["Sadanand Dhume",
            "James Freeman",
            "William A. Galston",
            "Daniel Henninger",
            "Holman W. Jenkins",
            "Andy Kessler",
            "William McGurn",
            "Walter Russell Mead",
            "Peggy Noonan",
            "Mary Anastasia O'Grady",
            "Jason Riley",
            "Joseph Sternberg",
            "Kimberley A. Strassel",],
        "Reviews": ["Books",
            "Film",
            "Television",
            "Theater",
            "Art",
            "Masterpiece Series",
            "Music",
            "Dance",
            "Opera",
            "Exhibition",
            "Cultural Commentary",],
        "More": ["Editorials",
            "Commentary",
            "Future View",
            "Letters to the Editor",
            "The Weekend Interview",
            "Potomac Watch Podcast",
            "Foreign Edition Podcast",
            "Opinion Video",
            "Notable & Quotable",
            "Best of the Web Newsletter",
            "Morning Editorial Report Newsletter",]
    },
    {
        "Sections": ["Arts",
            "Books",
            "Cars",
            "Food & Drink",
            "Health",
            "Ideas",
            "Reading & Retreating",
            "Real Estate",
            "Science",
            "Sports",
            "Style & Fashion",
            "Travel",],
        "More": ["WSJ. Magazine",
            "WSJ Puzzles",
            "The Future of Everything",
            "Far & Away",
            "Life Video",
            "Arts Video",]
    },
    {
        "Sections": ["Commercial Real Estate",
            "House of the Day",],
        "More": ["Real Estate Video"]
    },
    {
        "Sections": ["Fashion",
            "Art & Design",
            "Travel",
            "Food",
            "Culture",]
    }
]

export default sections;